### PR TITLE
Bugfix: Always emit a token from parse_atom

### LINKED ISSUE #43: Parser error with `peek_behind`
```
julia> JuliaSyntax.parseall(JuliaSyntax.GreenNode, "function")
ERROR: Internal error: Can't peek behind at start of stream
Stacktrace:
  [1] error(::String, ::String)
    @ Base ./error.jl:42
  [2] internal_error(strs::String)
    @ JuliaSyntax ~/.julia/dev/JuliaSyntax/src/parser.jl:220
  [3] peek_behind(stream::JuliaSyntax.ParseStream; skip_trivia::Bool)
    @ JuliaSyntax ~/.julia/dev/JuliaSyntax/src/parse_stream.jl:521
  [4] peek_behind
    @ ~/.julia/dev/JuliaSyntax/src/parse_stream.jl:503 [inlined]
  [5] #peek_behind#54
    @ ~/.julia/dev/JuliaSyntax/src/parser.jl:80 [inlined]
  [6] peek_behind
    @ ~/.julia/dev/JuliaSyntax/src/parser.jl:80 [inlined]
  [7] parse_function(ps::JuliaSyntax.ParseState)
    @ JuliaSyntax ~/.julia/dev/JuliaSyntax/src/parser.jl:2032
```

### PR DESCRIPTION
**Pull request by c42f**
If a closing token is found in parse_atom, we still need to emit a
nontrivia token to make the resulting parse tree consistent. We choose
an invisible token for this.

Also add various minor fixes to error recovory and a few additional
tests in parse_atom and elsewhere.

Fixes #43

### CODE REVIEW

File: src/parser.jl [hunk 1]
```diff
@@ -3375,14 +3381,16 @@ function parse_atom(ps::ParseState, check_identifiers=true)
...
     elseif is_closing_token(ps, leading_kind)
         # Leave closing token in place for other productions to 
-        # recover with (??)
+        # recover with
+        # )  ==>  error
         msg = leading_kind == K"EndMarker" ?
               "premature end of input" :
               "unexpected closing token"
-        emit_diagnostic(ps, error=msg)
+        bump_invisible(ps, K"error", error=msg)
```
Comment (c42f) [inline src/parser.jl:3393]: This is the actual bugfix
