### PR TITLE
Fix Expr conversion of erroneous operator dot call

### LINKED ISSUE #341: MethodError: no method matching `isless(::Int64, ::Nothing)`
MWE:

```julia
premc@DESKTOP-0UND5EL:/mnt/c/Users/premc/Documents/julia$ ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.235 (2023-08-06)
 _/ |\__'_|_|_|\__'_|  |  Commit 9f9e989f24 (1 day old master)
|__/                   |

julia> ./julia
┌ Error: JuliaSyntax parser failed — falling back to flisp!
│   exception =
│    MethodError: no method matching isless(::Int64, ::Nothing)
│ 
│    Closest candidates are:
│      isless(::Missing, ::Any)
│       @ Base missing.jl:87
│      isless(::Any, ::Missing)
│       @ Base missing.jl:88
│      isless(::Real, ::AbstractFloat)
│       @ Base operators.jl:178
│      ...
│ 
│    Stacktrace:
│      [1] <(x::Int64, y::Nothing)
│        @ Base ./operators.jl:352
│      [2] >(x::Nothing, y::Int64)
│        @ Base ./operators.jl:378
│      [3] core_parser_hook(code::String, filename::String, lineno::Int64, offset::Int64, options::Symbol)
│        @ Base.JuliaSyntax /mnt/c/Users/premc/Documents/julia/base/JuliaSyntax/src/hooks.jl:212
│      [4] invoke_in_world(::UInt64, ::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│        @ Base ./essentials.jl:921
│      [5] invoke_in_world(::UInt64, ::Any, ::Any, ::Vararg{Any})
│        @ Base ./essentials.jl:918
│      [6] (::Base.JuliaSyntax.var"#invoke_fixedworld#120"{Base.JuliaSyntax.var"#invoke_fixedworld#117#121"{typeof(Base.JuliaSyntax.core_parser_hook), UInt64}})(::String, ::Vararg{Any}; kws::@Kwargs{})
│        @ Base.JuliaSyntax /mnt/c/Users/premc/Documents/julia/base/JuliaSyntax/src/hooks.jl:118
│      [7] (::Base.JuliaSyntax.var"#invoke_fixedworld#120"{Base.JuliaSyntax.var"#invoke_fixedworld#117#121"{typeof(Base.JuliaSyntax.core_parser_hook), UInt64}})(::String, ::Vararg{Any})
│        @ Base.JuliaSyntax /mnt/c/Users/premc/Documents/julia/base/JuliaSyntax/src/hooks.jl:117
│      [8] _parse_string(text::String, filename::String, lineno::Int64, index::Int64, options::Symbol)
│        @ Base.Meta ./meta.jl:200
│      [9] #parseall#6
│        @ Base.Meta ./meta.jl:294 [inlined]
│     [10] parseall
│        @ Base.Meta ./meta.jl:293 [inlined]
│     [11] _parse_input_line_core
│        @ Base ./client.jl:174 [inlined]
│     [12] #parse_input_line#1032
│        @ Base ./client.jl:192 [inlined]
│     [13] parse_input_line
│        @ Base ./client.jl:189 [inlined]
│     [14] (::REPL.var"#93#103"{REPL.LineEditREPL, REPL.REPLHistoryProvider})(x::Any)
│        @ REPL /mnt/c/Users/premc/Documents/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1075
│     [15] #invokelatest#2
│        @ Base ./essentials.jl:887 [inlined]
│     [16] invokelatest
│        @ Base ./essentials.jl:884 [inlined]
│     [17] (::REPL.var"#do_respond#80"{Bool, Bool, REPL.var"#93#103"{REPL.LineEditREPL, REPL.REPLHistoryProvider}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
│        @ REPL /mnt/c/Users/premc/Documents/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:901
│     [18] #invokelatest#2
│        @ Base ./essentials.jl:887 [inlined]
│     [19] invokelatest
│        @ Base ./essentials.jl:884 [inlined]
│     [20] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit /mnt/c/Users/premc/Documents/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2656
│     [21] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
│        @ REPL /mnt/c/Users/premc/Documents/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1308
│     [22] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
│        @ REPL /mnt/c/Users/premc/Documents/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:384
│   offset = 0
│   code = "./julia"
└ @ Base.JuliaSyntax /mnt/c/Users/premc/Documents/julia/base/JuliaSyntax/src/hooks.jl:258
ERROR: syntax: "./" is not a unary operator
Stacktrace:
 [1] top-level scope
   @ none:1

julia> versioninfo()
Julia Version 1.11.0-DEV.235
Commit 9f9e989f24 (2023-08-06 04:35 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, icelake-client)
  Threads: 1 on 8 virtual cores
```

### PR DESCRIPTION
**Pull request by Liozou**
Fix #341

The root issue was the unconditional conversion of an `Expr(:dotcall, foo, ...)` to `Expr(:call, Symbol(:., foo), ...)` when `foo` was not an `Expr(:., ...)`. That case corresponds to dotted operators (where `foo` is the symbol of the operator), but it can actually also occur when there is a parsing error, such as misplacing a non-unitary dotted operator like in the MWE.

I'm not completely sure what `Expr` should be yielded here, I went for `Expr(:dotcall, Expr(:error, Expr(:., foo), ...)` because it required minimal change, but let me know if it should be something else!

### CODE REVIEW

**Comment by c42f** [comment]
Awesome, thanks for the PR!

As for the appropriate `Expr` here, we currently have the following conversion for `.+` (which of course is valid):

```julia
julia> parsestmt(SyntaxNode, ".+julia", ignore_errors=true)
line:col│ tree                                   │ file_name
   1:1  │[dotcall-pre]
   1:2  │  +
   1:3  │  julia


julia> dump(Expr(parsestmt(SyntaxNode, ".+julia", ignore_errors=true)))
Expr
  head: Symbol call
  args: Array{Any}((2,))
    1: Symbol .+
    2: Symbol julia
```

And we have the following tree for `./` which contains the error

```julia
julia> parsestmt(SyntaxNode, "./julia", ignore_errors=true)
line:col│ tree                                   │ file_name
   1:1  │[dotcall-pre]
   1:1  │  [error]
   1:1  │    [.]
   1:2  │      /
   1:3  │  julia
```

`Expr(:dotcall)` isn't something which consumers of `Expr` know about - they only know about `Expr(:call)` so I think we should go with the closest analogy using `Expr(:call)` that we can find. This should probably be `Expr(:call, Expr(:error, Expr(:., :/)), :julia)` ?

**Comment by Liozou** [comment]
That's perfectly sensible: done in https://github.com/JuliaLang/JuliaSyntax.jl/pull/374/commits/bea7bae2f3d6ff29ff1e820f1efbd832e714f0ea, thanks for the correction!

Another question: should I assert that `startsym` is either a `Symbol` or an `Expr(:error, ...)` at the following: https://github.com/JuliaLang/JuliaSyntax.jl/blob/bea7bae2f3d6ff29ff1e820f1efbd832e714f0ea/src/expr.jl#L276-L278
i.e. change the comment into an `else` clause that errors if `startsym` is not an `Expr(:error, ...)`? I don't know if the current policy is to eagerly error when encountering unexpected expressions at that point of the parser, or letting them flow.

File: test/expr.jl [hunk 1]
```diff
@@ -463,6 +463,12 @@
         @test parsestmt("f(.+)")   == Expr(:call, :f, Expr(:., :+))
         @test parsestmt("(a, .+)") == Expr(:tuple, :a, Expr(:., :+))
         @test parsestmt("A.:.+")   == Expr(:., :A, QuoteNode(Symbol(".+")))
+
+        # Issue #341
+        @test parsestmt("f(./x)", ignore_errors=true) == Expr(:call, :f,
+                                                            Expr(:call,
+                                                                Expr(:error, Expr(:., :/)),
+                                                                :x))
```
Comment (c42f) [inline test/expr.jl:471]: Just `parsestmt("./x", ignore_errors=true)` will do here for simplicity?

File: src/expr.jl [hunk 2]
```diff
@@ -266,13 +266,16 @@ function _internal_node_to_Expr(source, srcrange, head, childranges, childheads,
         # Move parameters blocks to args[2]
         _reorder_parameters!(args, 2)
         if headsym === :dotcall
+            startsym = args[1]
```
Comment (c42f) [inline src/expr.jl:269]: Naming quibble: this might not be a `Symbol` - it's just the function to be called, so maybe call it `callee` or `funcname` or something.  For example, consider how `(f()).(x,y)` parses.

**Review by c42f — COMMENTED** [review]
Thanks! I've noted a couple more minor quibbles, but I think this is basically good to go.

I'm in two minds about asserting that the `else` should be an `Expr(:error)`.  On the one hand, the parser shouldn't create any other forms.  But on the other hand, people can construct `SyntaxNode`s programmatically and it might make sense just to convert them rather than throw.  I don't really know. Maybe leave as-is :-)

**Comment by Liozou** [comment]
Thanks for the review, much better now!
I had somewhat similar hesitations regarding the error behaviour... But in any case this can be handled in a later PR if need be, it is not directly related to this bugfix anyway.

**Comment by c42f** [comment]
Looks lovely, thank youu :)

**Comment by Liozou** [comment]
Thank you for all the help!
