### PR TITLE
Permit parens in function call signatures

### LINKED ISSUE #116: Incorrect parsing of `function` with parens.
master:
```
julia> dump(:(function (f(::T) where {T}) end))
Expr
  head: Symbol function
  args: Array{Any}((2,))
    1: Expr
      head: Symbol where
      args: Array{Any}((2,))
        1: Expr
          head: Symbol call
          args: Array{Any}((2,))
            1: Symbol f
            2: Expr
              head: Symbol ::
              args: Array{Any}((1,))
                1: Symbol T
        2: Symbol T
    2: Expr
      head: Symbol block
      args: Array{Any}((2,))
        1: LineNumberNode
          line: Int64 1
          file: Symbol REPL[11]
        2: LineNumberNode
          line: Int64 1
          file: Symbol REPL[11]
```
JuliaSyntax
```
julia> dump(:(function (f(::T) where {T}) end))
Expr
  head: Symbol function
  args: Array{Any}((2,))
    1: Expr
      head: Symbol tuple
      args: Array{Any}((1,))
        1: Expr
          head: Symbol where
          args: Array{Any}((2,))
            1: Expr
              head: Symbol call
              args: Array{Any}((2,))
                1: Symbol f
                2: Expr
            2: Symbol T
    2: Expr
      head: Symbol block
      args: Array{Any}((2,))
        1: LineNumberNode
          line: Int64 1
          file: Symbol REPL[21]
        2: LineNumberNode
          line: Int64 1
          file: Symbol REPL[21]
```

### PR DESCRIPTION
**Pull request by c42f**
This permits the extra parentheses in things like

    function (funcname(some, long, argument, list)
              where {Type,Params})
        body
    end

This syntax "works" in the reference parser and has been seen in the wild so we need to support it for compatibility. (However, it's broken when combined with return type annotations which suggests it's more a syntactic aberration rather than an intentional feature.)

Fix #116

### CODE REVIEW

File: src/kinds.jl [hunk 1]
```diff
@@ -880,6 +880,7 @@ const _kind_names =
         "tuple"
         "ref"
         "vect"
+        "parens"
```
Comment (c42f) [inline src/kinds.jl:883]: This is here because I wanted to use it in the test harness, and because I expect to use it in the main parser later on, as part of #88

**Comment by pfitzseb** [comment]
> However, it's broken when combined with return type annotations which suggests it's more a syntactic aberration rather than an intentional feature.

Do you mean
```
function (funcname(some, long, argument, list)
          where {Type,Params})::Int
    body
end
```
If so, I don't think it's reasonable to expect that to work. The usual way of specifying return types via
```
function ((funcname(some, long, argument, list)::Int)
          where {Type,Params})::Int
    body
end
```
works fine afterall, even with the additional parens.

**Comment by c42f** [comment]
I mean you can't "just add grouping parens" without changing the relative precedence of `::` and `where`:

Ie, we can't go from the normal syntax

```julia
julia> function f(a::T)::T where T
           a
       end
f (generic function with 1 method)

julia> f(1)
1
```

To the same thing with parens without the precedence of `::` and `where` changing:

```julia
julia> function (g(a::T)::T where T)
           a
       end
ERROR: UndefVarError: T not defined
```

Additional parens (like in your example) are required to manually fix the precedence:

```julia
julia> function ((h(a::T)::T) where T)
           a
       end
h (generic function with 1 method)
```

all of which indicates to me that allowing parens here at all is probably just a bad idea. (Must be allowed for compatibility, though we could warn in future?)

**Comment by c42f** [comment]
I'm going to merge this now - the comment about this being bad syntax is just my opinion that this PR doesn't take a stance on (other than complaining about it in a code comment hehe)

**Comment by oscardssmith** [comment]
So fun fact: This broke parsing of
```
function (::A(B))()
1
end
 ```

**Comment by oscardssmith** [comment]
(This matters for ChainRulesCore https://github.com/JuliaDiff/ChainRulesCore.jl/blob/9c8fcd22ee1432bb1b1707215e09af4a1ae3b072/src/projection.jl#L34 which means that with this change pretty much every library that defines chain rules is broken with this).
